### ISSUE TITLE
Item quality border gone - Cata

### ISSUE THREAD

**Issue by mathwro** [Baganator/Baganator-ElvUI#1]
Hi!

The item border quality seem to be missing on the cata client atleast with the skin enabled

Thanks for the addon!

**Comment by plusmouse** [comment]
It isn't missing for me. Are you on the latest versions of ElvUI, Baganator and the skin?

**Comment by mathwro** [comment]
No skin:

![image](https://github.com/Baganator/Baganator-ElvUI/assets/16838008/77ba9cf0-48c2-49e4-9683-434ca1ed2032)

With skin:
![image](https://github.com/Baganator/Baganator-ElvUI/assets/16838008/29667fba-cd48-488b-bcee-6c83c260d1e2)


Im on these versions which should be the newest ones as i see
ElvUI: 13.66
Baganator: 297-cata
Skin: 0.6

**Comment by plusmouse** [comment]
Do you want your Masque skin applied, or are you looking for a pure ElvUI look? As its the Masque skin that's breaking the borders.

**Comment by mathwro** [comment]
Oh, that makes sense, completely forgot i even was running Masque. But ideally i would love that on top of your skin 😄

**Comment by plusmouse** [comment]
Good news, the latest alpha will now support your Masque skin with the ElvUI skin 😁 
[Baganator-ElvUI-0.6-1-g32ec4e3.zip](https://github.com/user-attachments/files/15732901/Baganator-ElvUI-0.6-1-g32ec4e3.zip)
Can you confirm it works for you?

**Comment by mathwro** [comment]
![image](https://github.com/Baganator/Baganator-ElvUI/assets/16838008/8905c3c2-51d2-4446-91ba-31a74d7bad07)

Works just as i was hoping for! Thanks!

**Comment by plusmouse** [comment]
Great 👍
