### ISSUE TITLE
Inappropriate font is displayed - Retail

### ISSUE THREAD

**Issue by Rubyurek** [Baganator/Baganator-ElvUI#2]
The default ElvUI font is displayed, although I would like to have the default font. The standard font I use is Friz Quadrata TT.

![font](https://github.com/Baganator/Baganator-ElvUI/assets/42946288/f4607def-d2ea-49ac-9c8d-84471c6c7793)

**Comment by plusmouse** [comment]
Enable the ElvUI bags, then change the Count font to Friz Quadrata TT, then disable the ElvUI bags to swap the font.
